### PR TITLE
l/D/TableReader.pm: typo proceeed → proceed.

### PR DESCRIPTION
**Pull request by emollier**

### CODE REVIEW

**Comment by emollier** [comment]
Thank you!
Have a nice day,  :)
Étienne.

**Comment by nrdvana** [comment]
Did you just happen to notice it, or was this part of an automated distro packaging check?

**Comment by emollier** [comment]
The typo was identified by lintian when I was proceeding to the packaging of the newer version during this evening's "Debian Perl packaging Low Hanging Fruit session" (LHF).

Cheers,
Étienne.

**Comment by nrdvana** [comment]
If I pre-screen my modules for typos, does that help streamline the distro packaging?  I've been meaning to add an author-test for that but never got around to it.

Thanks for the packaging effort.

**Comment by emollier** [comment]
Hi,

M Conrad, on 2024-06-21:
> If I pre-screen my modules for typos, does that help streamline the distro packaging?

That sure would be helpful.

Have a nice day,  :)
Étienne.

**Pull request merged**
